### ISSUE TITLE
Initial thoughts

### ISSUE THREAD

**Issue by inmysocks** [Zatnosk/libodonjs#1]
To preface this I think you probably know this stuff, but it is what I have done.

I am not sure if you have done anything past what the code you have up right now, but to start I am just going to list what I have here:

The app registering is the same as you have, but the next step is generally done with a redirect. The code for getting the access token in generally part of the redirect uri, but I haven't figured out how to get the redirect uri. I was skirting the problem by having a link open a new tab and the user had to copy the code from the newly opened tab into the application page.

The problem I ran into is that getting the token with an xmlhttprequest keeps failing, probably because of cors problems. I have no idea how to get past that.

After that the api requests should be simple enough. I hope that you have some solution to the redirect.

**Comment by Gargron** [comment]
@inmysocks The CORS problem on the /oauth/token endpoint has been resolved.

I recommend using some established library for the OAuth2 stuff. But the gist of it is, you redirect user to the authorize_url, then user comes back to your redirect_uri (ideally the same page as before) which now has a ?code query param which you can use to get the token.
