### ISSUE TITLE
License

### ISSUE THREAD

**Issue by snorpey** [Zatnosk/libodonjs#2]
Hi there!

I'd like to use some of the code in this repository in one of my projects, but I couldn't find anything about a license (or conditions for reuse). Would you mind mentioning this somewhere in the repo?

Thank you!

**Comment by Zatnosk** [comment]
Hi :)
Sorry for replying so slowly - I'm not used to checking notifications on github.
I'm glad you want to use my code! I haven't thought of licencing yet, but will look at it very soon.
If informality is ok, I'm definitely fine with you using it for whatever, and attribution is appreciated but not required :)

- Zatnosk

**Comment by Zatnosk** [comment]
I've assigned a MIT license to the code - if this conflicts with anything (I can't imagine how?) please let me know.
