### ISSUE TITLE
First example ?

### ISSUE THREAD

**Issue by DavidLibeau** [Zatnosk/libodonjs#4]
Hi, sorry for the inconvenience, but I tried to test this lib and the Mastodon API but I didn't succeed and don't know why.

Is there any simple runnable example to start with ?

For information, I've got this error while trying to do the `app.connect(server_url, user_email)` : 
```
Failed to find token in storage & no code found in URL parameters.
  get_token @ libodon.js:144
  get_registration.then.reg @ libodon.js:16
libodon.js:24 Uncaught (in promise) Object {error: "failed connection"}
  get_registration.then.then.error @ libodon.js:24
libodon.js:25 Uncaught (in promise) ReferenceError: reg is not defined
  get_registration.then.then.error @ libodon.js:25
```

Thanks

**Comment by Zatnosk** [comment]
I found a bug and fixed it. The code hasn't been tested that much and is still only half-finished, but feel free to use and/or improve it :)
